title: Boyun Li
position: Master Student
affiliation: Sichuan University, China
email: liboyun.gm@gmail.com
scholar: https://scholar.google.com/citations?hl=zh-CN&user=CnTYMosAAAAJ
keywords: Boyun Li
google_scholar: 
github_link: 
linkedin: 
avatar: ./assets/img/avatar.jpg
google_analytics: UA-111540567-4
favicon: 
favicon_dark: ./assets/img/favicon-dark.png
description: The Minimal Light is a simple and elegant jekyll theme for academic personal homepage.
canonical: https://minimal-light.yyliu.net/
remote_theme: liboyun.github.io
